# Generated by Django 6.0.5 on 2026-05-25 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['uploaded_at'], name='resumes_res_uploade_f96a7a_idx'),
        ),
    ]
