# Generated by Django 6.0.5 on 2026-05-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('ai_evaluation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['interview', 'created_at'], name='interviews__intervi_9a358e_idx')],
            },
        ),
    ]
